name: 'MT Tenant Creation'
description: 'Run the package with user-defined parameters'
inputs:
  tenant:
    description: 'The name of the new tenant to be created (i.e. JUPITER)'
    required: true
  bundleId:
    description: 'The bundle id of the new tenant to be created (i.e. com.angeleye.MT.jupiter)'
    required: true
  baseURL:
    description: 'Base url for the new tenant (i.e. MT.jmc.com). https will be automatically appended'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    
    - name: Install curl (for rustup)
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y curl wget
           curl --version  # Ensure curl is installed

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build Rust package
      shell: bash
      run: cargo build --release
      working-directory: ${{ github.workspace }}/rust-tenantizer

    - name: Run Rust package
      shell: bash
      run: ./target/release/tenantize "${{ inputs.tenant }}" "${{ inputs.baseURL }}" "${{ inputs.bundleId }}"
      working-directory: ${{ github.workspace }}/rust-tenantizer